PROCESS-NAME,/Applications/Thunder.app/
# NAME: Epic
DOMAIN-SUFFIX,battlebreakers.com
DOMAIN-SUFFIX,eac-cdn.com
DOMAIN-SUFFIX,easy.ac
DOMAIN-SUFFIX,easyanticheat.net
DOMAIN-SUFFIX,epicgames.com
DOMAIN-SUFFIX,epicgames.dev
DOMAIN-SUFFIX,fortnite.com
DOMAIN-SUFFIX,helpshift.com
DOMAIN-SUFFIX,paragon.com
DOMAIN-SUFFIX,playparagon.com
DOMAIN-SUFFIX,roborecall.com
DOMAIN-SUFFIX,shadowcomplex.com
DOMAIN-SUFFIX,spyjinx.com
DOMAIN-SUFFIX,unrealengine.com
DOMAIN-SUFFIX,unrealtournament.com
IP-CIDR,47.246.138.133/32
IP-CIDR,59.82.120.242/32
IP-CIDR,47.246.177.10/32
