PROCESS-NAME,/Applications/Copilot.app/Contents/MacOS/Copilot
DOMAIN-SUFFIX,docker.com
DOMAIN-SUFFIX,downloadtorrentfile.com
DOMAIN-SUFFIX,brew.sh
DOMAIN-SUFFIX,debian.org
DOMAIN-SUFFIX,imdb.com
DOMAIN-SUFFIX,imdb.to
DOMAIN-SUFFIX,media-imdb.com
DOMAIN-SUFFIX,immersivetranslate.com
PROCESS-NAME,"/Applications/Tor Browser.app/"
DOMAIN-KEYWORD,minimax
DOMAIN-SUFFIX,atom.io
DOMAIN-SUFFIX,dependabot.com
DOMAIN-SUFFIX,ghcr.io
DOMAIN-SUFFIX,git.io
DOMAIN-SUFFIX,github-atom-io-herokuapp-com.freetls.fastly.net
DOMAIN-SUFFIX,github-avatars.oss-cn-hongkong.aliyuncs.com
DOMAIN-SUFFIX,github-cloud.s3.amazonaws.com
DOMAIN-SUFFIX,github.blog
DOMAIN-SUFFIX,github.com
DOMAIN-SUFFIX,github.community
DOMAIN-SUFFIX,github.dev
DOMAIN-SUFFIX,github.io
DOMAIN-SUFFIX,githubapp.com
DOMAIN-SUFFIX,githubassets.com
DOMAIN-SUFFIX,githubcopilot.com
DOMAIN-SUFFIX,githubhackathon.com
DOMAIN-SUFFIX,githubnext.com
DOMAIN-SUFFIX,githubpreview.dev
DOMAIN-SUFFIX,githubstatus.com
DOMAIN-SUFFIX,githubuniverse.com
DOMAIN-SUFFIX,githubusercontent.com
DOMAIN-SUFFIX,myoctocat.com
DOMAIN-SUFFIX,npm.community
DOMAIN-SUFFIX,npmjs.com
DOMAIN-SUFFIX,npmjs.org
DOMAIN-SUFFIX,opensource.guide
DOMAIN-SUFFIX,rawgit.com
DOMAIN-SUFFIX,rawgithub.com
DOMAIN-SUFFIX,repo.new
DOMAIN-SUFFIX,thegithubshop.com
DOMAIN-KEYWORD,github
DOMAIN-SUFFIX,kagi.com
IP-CIDR,91.105.192.0/23
IP-CIDR,91.108.4.0/22
IP-CIDR,91.108.8.0/21
IP-CIDR,91.108.16.0/21
IP-CIDR,91.108.56.0/22
IP-CIDR,95.161.64.0/20
IP-CIDR,149.154.160.0/20
IP-CIDR,185.76.151.0/24
IP-CIDR6,2001:67c:4e8::/48
IP-CIDR6,2001:b28:f23c::/47
IP-CIDR6,2001:b28:f23f::/48
IP-CIDR6,2a0a:f280::/32
