DOMAIN-SUFFIX,docker.com
DOMAIN-SUFFIX,downloadtorrentfile.com
DOMAIN-SUFFIX,brew.sh
DOMAIN-SUFFIX,debian.org
DOMAIN-SUFFIX,imdb.com
DOMAIN-SUFFIX,imdb.to
DOMAIN-SUFFIX,media-imdb.com
DOMAIN-SUFFIX,immersivetranslate.com
PROCESS-NAME,"/Applications/Tor Browser.app/"
DOMAIN-KEYWORD,minimax
